apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
  annotations: {}
  labels: {}
description: prod
requireApproval: true
gke:
  cluster: projects/utopian-bonito-347816/locations/us-central1-c/clusters/helm-cd-testing-prd
