apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
  annotations: {}
  labels: {}
description: staging
gke:
  cluster: projects/<project-id>/locations/<zone>/clusters/helm-cd-testing-stg
