apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
  annotations: {}
  labels: {}
description: staging
gke:
  cluster: projects/dulcet-timing-429804-a6/locations/us-central1/clusters/helm-cd-testing-stg
